### ISSUE TITLE
Task execution ?

### ISSUE THREAD

**Issue by gestom** [strands-project/strands_executive#173]
## execution_queue: 

```
task_id: 6
start_node_id: WayPoint5
end_node_id: WayPoint5
action: /info_task_server
start_after: 
  secs: 1428609605
  nsecs: 0
end_before: 
  secs: 1428609898
  nsecs: 0
max_duration: 
  secs: 180
  nsecs: 0
execution_time: 
  secs: 1428609605
  nsecs: 0
arguments: []
```
- 
  task_id: 7
  start_node_id: WayPoint4
  end_node_id: WayPoint4
  action: /info_task_server
  start_after: 
    secs: 1428609905
    nsecs: 0
  end_before: 
    secs: 1428610198
    nsecs: 0
  max_duration: 
    secs: 180
    nsecs: 0
  execution_time: 
    secs: 1428609905
    nsecs: 0
  arguments: []
  ---
  -------------------------------------------------------------------------------------------------------------------------------
  And:
  rosservice call /task_executor/get_execution_status 
  status: True
  -------------------------------------------------------------------------------------------------------------------------------

But the robot does not do anything.
