### ISSUE TITLE
duplicated task in /current_schedule

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_executive#224]
Our `/current_schedule` looks like this at the moment:

```
strands@werner:~$ rostopic echo /current_schedule                                                                                                            
currently_executing: True                                                                                                                                    
execution_queue:                                                                                                                                             
  -                                                                                                                                                          
    task_id: 2                                                                                                                                               
    start_node_id: ChargingPoint                                                                                                                             
    end_node_id: ChargingPoint                                                                                                                               
    action: /info_task_server                                                                                                                                
    start_after:                                                                                                                                             
      secs: 1458752400                                                                                                                                       
      nsecs: 0                                                                                                                                               
    end_before:                                                                                                                                              
      secs: 1458763200                                                                                                                                       
      nsecs: 0                                                                                                                                               
    max_duration:                                                                                                                                            
      secs: 10800                                                                                                                                            
      nsecs: 0                                                                                                                                               
    execution_time:                                                                                                                                          
      secs: 1458752400                                                                                                                                       
      nsecs: 0                                                                                                                                               
    priority: 2                                                                                                                                              
    arguments: []                                                                                                                                            
  -                                                                                                                                                          
    task_id: 2                                                                                                                                               
    start_node_id: ChargingPoint                                                                                                                             
    end_node_id: ChargingPoint                                                                                                                               
    action: /info_task_server                                                                                                                                
    start_after:                                                                                                                                             
      secs: 1458752400                                                                                                                                       
      nsecs: 0                                                                                                                                               
    end_before:                                                                                                                                              
      secs: 1458763200                                                                                                                                       
      nsecs: 0                                                                                                                                               
    max_duration:                                                                                                                                            
      secs: 10800                                                                                                                                            
      nsecs: 0                                                                                                                                               
    execution_time:                                                                                                                                          
      secs: 1458752400                                                                                                                                       
      nsecs: 0                                                                                                                                               
    priority: 2                                                                                                                                              
    arguments: []                                                                                                                                            
--- 
```

`get_active_task` looks alright:

```
strands@werner:~$ rosservice call /task_executor/get_active_task                                                                                             
task:                                                                                                                                                        
  task_id: 2                                                                                                                                                 
  start_node_id: ChargingPoint                                                                                                                               
  end_node_id: ChargingPoint                                                                                                                                 
  action: /info_task_server                                                                                                                                  
  start_after:                                                                                                                                               
    secs: 1458752400                                                                                                                                         
    nsecs: 0                                                                                                                                                 
  end_before:                                                                                                                                                
    secs: 1458763200                                                                                                                                         
    nsecs: 0                                                                                                                                                 
  max_duration:                                                                                                                                              
    secs: 10800                                                                                                                                              
    nsecs: 0                                                                                                                                                 
  execution_time:                                                                                                                                            
    secs: 1458752400                                                                                                                                         
    nsecs: 0                                                                                                                                                 
  priority: 2                                                                                                                                                
  arguments: [] 
```

and execution-status was `True` as well.
